config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: :show
  devise_for :users
  root 'pages#home'
  # get '/home',to: 'pages#home'
  get '/about',to: 'pages#about_us'
  get '/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
 belongs_to :user
 validates_presence_of :description, :due_date
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  def about_us
  end
  def contact
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @tasks = Task.where(user_id: current_user.id)
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper
    if current_user
     (link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link")
   else
     (link_to "Log in", new_user_session_path, class: "nav-link")
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    js add_gritter(messages , title: "ToDoList")

    # html = <<-HTML
    # <!-- <div id="error_explanation">
    #   <h2>#{sentence}</h2>
    #   <ul>#{messages}</ul>
    # </div> -->
    # HTML

  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTodoApp</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

      <%= render 'shared/alerts' %>
      <!-- <%= login_helper %> -->
      <div class="container">
          <%= yield %>
      </div>
   <hr>
   <div class="container">
    <footer>
      <p>&copy; Gaurav Gulati 2017</p>
    </footer>
  </div>



  </body>
  </html>

app/views/pages/about_us.html.erb
<br>
<h1 class="text-center"> About me</h1>

<hr>

<div class="row">
<div class="col-md-1"></div>
<div class="col-md-4">

<%= image_tag "GAURAVGULATI.jpg", width: "220", height: "270" %>

</div>


<div class="col-md-7">


<p> Gaurav Gulati, an individual who was always fascinated about the world wide web always wanted to
learn how complex web applications were built. But he did not find anything during his schooling that he can call as
his passion. With the guidance of others he started pursuing his Btech. Two years passed and he still was at directionless.
But destiny took him to the beautifull door of Ruby on Rails. He was quite fascinated by the popularity and thr functionality that RoR provided.
Later on, he started to develop web apps using RoR and still enjoys it.
</p>
<blockquote>
    - Gaurav Gulati
</blockquote>

</div>

</div>

app/views/pages/contact.html.erb
<br><br>
<h1> Get in Touch </h1>
<div class="row">
<div class="col-md-6">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3507.6721436085095!2d77.09262971618386!3d28.459298008090705!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d18cef60344f9%3A0xa1eaea631cac78fb!2sDell!5e0!3m2!1sen!2sin!4v1502276340260" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<div class="col-md-6">
  <br><br>
  <p><b> Email me </b>  : gauravgulati9c@gmail.com
    <p><b> Phone no. </b> : 78384xxxxx</p>
  </p>
</div>
</div>

app/views/pages/home.html.erb
<!-- <h1>Welcome To DailyTasks.com</h1> -->
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3 element"><i class="fa fa-list-ul" aria-hidden="true"></i> To Do List</h1>
    <p>This is a template for a simple To do List to increase your productivity. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
     <% if current_user %>
       <%= link_to 'New Task', new_task_path, class: "btn btn-primary btn-lg" %>
     <% else %>
       <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
     <% end %>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert] , title: "ToDoList") %>
<% elsif flash[:error]   %>
  <%= js add_gritter(flash[:error] , title: "ToDoList") %>
<% else %>
  <%= js add_gritter(flash[:notice] , title: "ToDoList") %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"><i class="fa fa-list-ul" aria-hidden="true"></i>ToDoList</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= login_helper %>
      </li>
      <% if current_user %>
      <li>
        <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
    <li class="form-inline my-2 my-lg-0">
      <a class="nav-link disabled" href="#">Gaurav Gulati</a>
    </li>


  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
      <% task.errors.full_messages.each do |message| %>
        <%= js add_gritter(message , title: "ToDoList") %>
      <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label "Description" %>
    <%= f.text_area :description, class: "form-control", rows:3, placeholder: "Whats on your Mind?" %>
  </div>

  <div class="form-group">
    <%= f.label "Due Date" %>
    <%= f.date_field :due_date, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit",class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="jumbotron">
  <h1 class="display-3"> <%= Time.now.strftime("%m/%d/%Y") %> </h1>
  <p class="lead">Make your day more productive with every work in your list <i class="fa fa-check fa-2x" aria-hidden="true"></i>.</p>
  <hr class="my-4">
  <p class="lead">
  <%= link_to 'New Task', new_task_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

    <% if @tasks.empty? %>
        <h1> No pending work to be done. Have a Break...!!! </h1>
    <% else %>
    <% @tasks.each do |task| %>
    <div class="card text-center">
      <div class="card-header">
        Task
      </div>
      <div class="card-body">
        <h4 class="card-title">  <%= task.description %></h4>
        <p class="card-text"><%= task.due_date %></p>
        <%= link_to 'Edit', edit_task_path(task), class: "btn btn-warning" %>
        <%= link_to 'Mark as Completed', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %>
      </div>
      <div class="card-footer text-muted">
        created <%= time_ago_in_words(task.created_at) %> ago
      </div>
    </div>
     <br>



    <% end %>
    <% end %>
<br>

app/views/tasks/new.html.erb
<br>

<h1>Create New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>